version: '3.9'

services:
  covid19_1:
    image: alvarodelcastillo/covid19swarm:0.1
    build: .
    ports:
      - "40001:8000"
    deploy:
      replicas: 3
      update_config:
        delay: 10s

  redis:
    image: redis:alpine
